// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzsUvFzEc62W8AgQRD76Nn4Ho6hYtDL6I',
    appId: '1:583449756071:web:ed7a0744ef33485f7fb682',
    messagingSenderId: '583449756071',
    projectId: 'bizzprice-39f54',
    authDomain: 'bizzprice-39f54.firebaseapp.com',
    storageBucket: 'bizzprice-39f54.firebasestorage.app',
    measurementId: 'G-1289MPNW2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbU5O7ijU-2ScIlYuMIPKGfYkmRaAa54',
    appId: '1:583449756071:android:379b343d95c166ae7fb682',
    messagingSenderId: '583449756071',
    projectId: 'bizzprice-39f54',
    storageBucket: 'bizzprice-39f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRD_-HTbPCqo_BwYare9Q2aLMlK55kJDg',
    appId: '1:583449756071:ios:c8ed969232dda41b7fb682',
    messagingSenderId: '583449756071',
    projectId: 'bizzprice-39f54',
    storageBucket: 'bizzprice-39f54.firebasestorage.app',
    iosBundleId: 'com.example.pblKelompok4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRD_-HTbPCqo_BwYare9Q2aLMlK55kJDg',
    appId: '1:583449756071:ios:c8ed969232dda41b7fb682',
    messagingSenderId: '583449756071',
    projectId: 'bizzprice-39f54',
    storageBucket: 'bizzprice-39f54.firebasestorage.app',
    iosBundleId: 'com.example.pblKelompok4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzsUvFzEc62W8AgQRD76Nn4Ho6hYtDL6I',
    appId: '1:583449756071:web:0af8ad0610749c0a7fb682',
    messagingSenderId: '583449756071',
    projectId: 'bizzprice-39f54',
    authDomain: 'bizzprice-39f54.firebaseapp.com',
    storageBucket: 'bizzprice-39f54.firebasestorage.app',
    measurementId: 'G-50QEHZKZVJ',
  );
}
